export enum NotificationType {
  JOIN_REQUEST = "JOIN_REQUEST",
  CLUB_REQUEST_ACCEPTED = "CLUB_REQUEST_ACCEPTED",
  CLUB_REQUEST_REJECTED = "CLUB_REQUEST_REJECTED",
  REMOVED_FROM_CLUB = "REMOVED_FROM_CLUB",
  EVENTS = "EVENTS",
  CLUB_CREATED = "CLUB_CREATED",
  GENERAL_ANNOUNCEMENT = "GENERAL_ANNOUNCEMENT",
  FRIEND_REQUEST = "FRIEND_REQUEST",
  FRIEND_REQUEST_ACCEPTED = "FRIEND_REQUEST_ACCEPTED",
}
